In [ ]:
#python -m venv solvingerror_venv #create the venv
python3 -m venv solvingerror_venv #create the venv

#solvingerror_venv\Scripts\activate #activate venv (windows)
source solvingerror_venv/bin/activate #(linux)

In [1]:
!python3 -m pip install ipykernel -U --user --force-reinstall

ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

In [3]:
!python3 --version

Python 3.12.3

In [ ]:
!pip install pandas

In [4]:
1+1

2

In [6]:
import json

with open('Spliit Export - 2025-02-01.json', 'r') as f:
    data = json.load(f)

# Now you can access the data just like in the previous example
trip_id = data['id']
#... and so on

In [8]:
import json

# Accessing top-level elements
trip_id = data['id']
trip_name = data['name']
currency = data['currency']

print(f"Trip ID: {trip_id}")
print(f"Trip Name: {trip_name}")
print(f"Currency: {currency}")


# Accessing expenses
expenses = data['expenses']
for expense in expenses:
    expense_date = expense['expenseDate']
    title = expense['title']
    category_grouping = expense['category']['grouping']
    category_name = expense['category']['name']
    amount = expense['amount']
    paid_by_id = expense['paidById']
    paid_for = expense['paidFor']  # This is a list of dictionaries
    is_reimbursement = expense['isReimbursement']
    split_mode = expense['splitMode']

    print(f"\nExpense Date: {expense_date}")
    print(f"Title: {title}")
    print(f"Category: {category_grouping} - {category_name}")
    print(f"Amount: {amount}")
    print(f"Paid by ID: {paid_by_id}")
    print("Paid for:")
    for person in paid_for:
        participant_id = person['participantId']
        shares = person['shares']
        print(f"  Participant ID: {participant_id}, Shares: {shares}")
    print(f"Is Reimbursement: {is_reimbursement}")
    print(f"Split Mode: {split_mode}")

# Accessing participants
participants = data['participants']
for participant in participants:
    participant_id = participant['id']
    participant_name = participant['name']
    print(f"\nParticipant ID: {participant_id}")
    print(f"Participant Name: {participant_name}")


# Example: Calculating total expenses
total_expenses = sum(expense['amount'] for expense in expenses)
print(f"\nTotal Expenses: {total_expenses}")

#Example: finding expenses in a certain category
hotel_expenses = [expense for expense in expenses if expense['category']['name'] == 'Hotel']

print("\nHotel Expenses")
for expense in hotel_expenses:
    print(expense['title'], expense['amount'])

Trip ID: KgJ5jZ-RkJbtehfB0mS-V
Trip Name: Thailand2025
Currency: pln

Expense Date: 2024-12-27T00:00:00.000Z
Title: Hote booking at Phuket Meet Holiday Hotel-Rawai
Category: Transportation - Hotel
Amount: 152300
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2024-12-29T00:00:00.000Z
Title: namaka resort kamala
Category: Transportation - Hotel
Amount: 165200
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2024-12-31T00:00:00.000Z
Title: phi phi hotel
Category: Transportation - Hotel
Amount: 191300
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2024-12-31T00:00:00.000Z
Title: Closing 2024
Category: Uncategorized - General
Amount: 60000
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-03T00:00:00.000Z
Title: Rent January 2025
Category: Home - Home
Amount: 551173
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-10T00:00:00.000Z
Title: comidas d1 cash
Category: Food and Drink - Food and Drink
Amount: 6600
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-11T00:00:00.000Z
Title: masajes D1
Category: Entertainment - Entertainment
Amount: 7200
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-11T00:00:00.000Z
Title: Media diciembre de casa
Category: Home - Mortgage
Amount: 44669
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-11T00:00:00.000Z
Title: taxi aero phuket
Category: Transportation - Transportation
Amount: 8000
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-09T00:00:00.000Z
Title: yo sushi qatar
Category: Uncategorized - General
Amount: 12000
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-11T00:00:00.000Z
Title: sim  100gb
Category: Uncategorized - General
Amount: 5400
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-11T00:00:00.000Z
Title: Bebidas d2
Category: Uncategorized - General
Amount: 1200
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-11T00:00:00.000Z
Title: Comida D2 phuket
Category: Food and Drink - Food and Drink
Amount: 12000
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-11T00:00:00.000Z
Title: corte pelo
Category: Entertainment - Entertainment
Amount: 2100
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-12T00:00:00.000Z
Title: D3 comida cafe mao
Category: Food and Drink - Food and Drink
Amount: 5600
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-12T00:00:00.000Z
Title: last hotel kamala
Category: Transportation - Hotel
Amount: 30700
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-12T00:00:00.000Z
Title: D3 comida gambas
Category: Food and Drink - Food and Drink
Amount: 1400
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-12T00:00:00.000Z
Title: D3 cena
Category: Food and Drink - Food and Drink
Amount: 1400
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-12T00:00:00.000Z
Title: D3 laundry
Category: Uncategorized - General
Amount: 1700
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-12T00:00:00.000Z
Title: D3 compare en super Tops
Category: Food and Drink - Groceries
Amount: 1700
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-14T00:00:00.000Z
Title: Mango rawai
Category: Food and Drink - Food and Drink
Amount: 950
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-14T00:00:00.000Z
Title: Avia rawai
Category: Food and Drink - Food and Drink
Amount: 300
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-14T00:00:00.000Z
Title: Phuket a PhiPhi - quick boat
Category: Transportation - Transportation
Amount: 26200
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-13T00:00:00.000Z
Title: starbucks digital creation
Category: Entertainment - Entertainment
Amount: 0
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-13T00:00:00.000Z
Title: taxi a rawaj
Category: Transportation - Transportation
Amount: 3800
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-13T00:00:00.000Z
Title: D4 comida rawaj
Category: Food and Drink - Food and Drink
Amount: 9700
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-14T00:00:00.000Z
Title: D5 cena
Category: Food and Drink - Food and Drink
Amount: 8200
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-14T00:00:00.000Z
Title: hotel krabi
Category: Home - Home
Amount: 67300
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-15T00:00:00.000Z
Title: D6 cena 5 stars
Category: Food and Drink - Food and Drink
Amount: 16200
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-15T00:00:00.000Z
Title: d6 taxi a kamala 5 star
Category: Transportation - Transportation
Amount: 7200
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-16T00:00:00.000Z
Title: d7 jet ski 20 min 1100cc Yamaha
Category: Entertainment - Entertainment
Amount: 18200
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-16T00:00:00.000Z
Title: d7 comida y zumo
Category: Food and Drink - Food and Drink
Amount: 5300
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-16T00:00:00.000Z
Title: d7 masage
Category: Entertainment - Entertainment
Amount: 7200
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-16T00:00:00.000Z
Title: d7 cena hotel
Category: Food and Drink - Food and Drink
Amount: 12400
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-16T00:00:00.000Z
Title: hotel aquamarine duplicated
Category: Transportation - Hotel
Amount: 0
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-17T00:00:00.000Z
Title: taxi kamala beach a rassada pier
Category: Transportation - Transportation
Amount: 10800
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-17T00:00:00.000Z
Title: D8 comida
Category: Food and Drink - Food and Drink
Amount: 4800
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-18T00:00:00.000Z
Title: ezcursion phiphi
Category: Entertainment - Entertainment
Amount: 27800
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-18T00:00:00.000Z
Title: d9 comida
Category: Food and Drink - Food and Drink
Amount: 4500
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-18T00:00:00.000Z
Title: 7eleven
Category: Food and Drink - Food and Drink
Amount: 2600
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-18T00:00:00.000Z
Title: Creams despise de sun
Category: Life - Medical Expenses
Amount: 5500
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-18T00:00:00.000Z
Title: Phone cases waterproof
Category: Uncategorized - General
Amount: 2400
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-18T00:00:00.000Z
Title: d9 long boat taxi
Category: Transportation - Transportation
Amount: 2400
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-19T00:00:00.000Z
Title: Tax for maya beach
Category: Life - Taxes
Amount: 9600
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-19T00:00:00.000Z
Title: D10 comida
Category: Food and Drink - Food and Drink
Amount: 3600
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-19T00:00:00.000Z
Title: Boat to the beach resort
Category: Transportation - Transportation
Amount: 3600
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-19T00:00:00.000Z
Title: boat phiphi krawi
Category: Transportation - Transportation
Amount: 12000
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-20T00:00:00.000Z
Title: hotel kho yqo yai 28 31ja
Category: Transportation - Hotel
Amount: 168700
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-21T00:00:00.000Z
Title: D11 cena y varios smoothies
Category: Food and Drink - Food and Drink
Amount: 18500
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-21T00:00:00.000Z
Title: D12 comidas y 7/11
Category: Food and Drink - Food and Drink
Amount: 3200
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-21T00:00:00.000Z
Title: Taxi krabi port to bluemonkey
Category: Transportation - Taxi
Amount: 2000
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-22T00:00:00.000Z
Title: D13 kayak krabi
Category: Entertainment - Entertainment
Amount: 19700
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-22T00:00:00.000Z
Title: D13 recogida a kayak
Category: Transportation - Transportation
Amount: 6000
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-22T00:00:00.000Z
Title: Desayuno
Category: Food and Drink - Food and Drink
Amount: 4300
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-22T00:00:00.000Z
Title: Lunch
Category: Food and Drink - Food and Drink
Amount: 1550
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-22T00:00:00.000Z
Title: D13 ropa krabi (Toki)
Category: Uncategorized - General
Amount: 1600
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-22T00:00:00.000Z
Title: Roti banana x3
Category: Food and Drink - Food and Drink
Amount: 700
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-23T00:00:00.000Z
Title: Transports a ko yao noi
Category: Transportation - Transportation
Amount: 4800
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-23T00:00:00.000Z
Title: d13 masage
Category: Entertainment - Entertainment
Amount: 8700
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-23T00:00:00.000Z
Title: Comida
Category: Food and Drink - Food and Drink
Amount: 2400
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-23T00:00:00.000Z
Title: tpt krabi ko yao yoi
Category: Transportation - Transportation
Amount: 12000
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-23T00:00:00.000Z
Title: Comida + piciu
Category: Food and Drink - Food and Drink
Amount: 1300
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-23T00:00:00.000Z
Title: Merienda ko Yao noi
Category: Food and Drink - Food and Drink
Amount: 9000
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-23T00:00:00.000Z
Title: Dinner
Category: Food and Drink - Food and Drink
Amount: 3300
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-25T00:00:00.000Z
Title: D16 bici
Category: Entertainment - Entertainment
Amount: 4800
Paid by ID: 3lNLhHQKb1t7WnMKMxiqb
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 100
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 100
Is Reimbursement: False
Split Mode: EVENLY

Expense Date: 2025-01-25T00:00:00.000Z
Title: Comida
Category: Food and Drink - Food and Drink
Amount: 9600
Paid by ID: 1NUuvMekM2Wm-mnEmLIld
Paid for:
  Participant ID: 1NUuvMekM2Wm-mnEmLIld, Shares: 1
  Participant ID: 3lNLhHQKb1t7WnMKMxiqb, Shares: 1
Is Reimbursement: False
Split Mode: EVENLY


In [9]:
import json
from collections import defaultdict

expenses_by_id_and_category = defaultdict(lambda: defaultdict(int))

for expense in data['expenses']:
    paid_by_id = expense['paidById']
    category_name = expense['category']['name']
    amount = expense['amount']

    expenses_by_id_and_category[paid_by_id][category_name] += amount

# Print the results
for paid_by_id, categories in expenses_by_id_and_category.items():
    print(f"\nExpenses paid by {paid_by_id}:")
    for category_name, total_amount in categories.items():
        print(f"  {category_name}: {total_amount}")

Expenses paid by 3lNLhHQKb1t7WnMKMxiqb:
  Hotel: 708200
  Food and Drink: 126200
  Transportation: 108000
  General: 13600
  Entertainment: 88500
  Home: 67300
  Taxi: 8700

Expenses paid by 1NUuvMekM2Wm-mnEmLIld:
  General: 70700
  Home: 551173
  Entertainment: 7200
  Mortgage: 44669
  Food and Drink: 93868
  Groceries: 1700
  Medical Expenses: 5500
  Taxes: 9600
  Transportation: 14034

In [11]:
import json
from collections import defaultdict

# with open('test.json', 'r') as f:
#     data = json.load(f)

expenses_by_category = defaultdict(int)

for expense in data['expenses']:
    category_name = expense['category']['name']
    amount = expense['amount']

    expenses_by_category[category_name] += amount

# Print the results
print("\nTotal expenses by category:")
for category_name, total_amount in expenses_by_category.items():
    print(f"  {category_name}: {total_amount}")

Total expenses by category:
  Hotel: 708200
  General: 84300
  Home: 618473
  Food and Drink: 220068
  Entertainment: 95700
  Mortgage: 44669
  Transportation: 122034
  Groceries: 1700
  Medical Expenses: 5500
  Taxes: 9600
  Taxi: 8700

In [13]:
import json
import pandas as pd
from collections import defaultdict

with open('Spliit Export - 2025-02-01.json', 'r') as f:
    data = json.load(f)

expenses_by_category = defaultdict(int)

for expense in data['expenses']:
    category_name = expense['category']['name']
    amount = expense['amount']
    expenses_by_category[category_name] += amount

# Convert to pandas DataFrame
df = pd.DataFrame(list(expenses_by_category.items()), columns=['Category', 'Total Expenses'])

print(df)


#If you want to group by ID and category, you can do this:

expenses_by_id_and_category = defaultdict(lambda: defaultdict(int))

for expense in data['expenses']:
    paid_by_id = expense['paidById']
    category_name = expense['category']['name']
    amount = expense['amount']

    expenses_by_id_and_category[paid_by_id][category_name] += amount

# Convert to a list of dictionaries for DataFrame creation
data_for_df = []
for paid_by_id, categories in expenses_by_id_and_category.items():
    for category_name, total_amount in categories.items():
        data_for_df.append({'Paid By': paid_by_id, 'Category': category_name, 'Total Expenses': total_amount})

df_id_cat = pd.DataFrame(data_for_df)

print("\nDataFrame Grouped by ID and Category:")
print(df_id_cat)


#If you want to keep all the expense details in the dataframe:

expenses_list = []
for expense in data['expenses']:
    expenses_list.append({
        'Expense Date': expense['expenseDate'],
        'Title': expense['title'],
        'Category': expense['category']['name'],
        'Grouping': expense['category']['grouping'],
        'Amount': expense['amount'],
        'Paid By': expense['paidById'],
        # ... other fields as needed
    })

df_all_expenses = pd.DataFrame(expenses_list)
print("\nDataFrame with all expenses:")
print(df_all_expenses)

            Category  Total Expenses
0              Hotel          708200
1            General           84300
2               Home          618473
3     Food and Drink          220068
4      Entertainment           95700
5           Mortgage           44669
6     Transportation          122034
7          Groceries            1700
8   Medical Expenses            5500
9              Taxes            9600
10              Taxi            8700

DataFrame Grouped by ID and Category:
                  Paid By          Category  Total Expenses
0   3lNLhHQKb1t7WnMKMxiqb             Hotel          708200
1   3lNLhHQKb1t7WnMKMxiqb    Food and Drink          126200
2   3lNLhHQKb1t7WnMKMxiqb    Transportation          108000
3   3lNLhHQKb1t7WnMKMxiqb           General           13600
4   3lNLhHQKb1t7WnMKMxiqb     Entertainment           88500
5   3lNLhHQKb1t7WnMKMxiqb              Home           67300
6   3lNLhHQKb1t7WnMKMxiqb              Taxi            8700
7   1NUuvMekM2Wm-mnEmLIld           General           70700
8   1NUuvMekM2Wm-mnEmLIld              Home          551173
9   1NUuvMekM2Wm-mnEmLIld     Entertainment            7200
10  1NUuvMekM2Wm-mnEmLIld          Mortgage           44669
11  1NUuvMekM2Wm-mnEmLIld    Food and Drink           93868
12  1NUuvMekM2Wm-mnEmLIld         Groceries            1700
13  1NUuvMekM2Wm-mnEmLIld  Medical Expenses            5500
14  1NUuvMekM2Wm-mnEmLIld             Taxes            9600
15  1NUuvMekM2Wm-mnEmLIld    Transportation           14034

DataFrame with all expenses:
                Expense Date  \
0   2024-12-27T00:00:00.000Z
1   2024-12-29T00:00:00.000Z
2   2024-12-31T00:00:00.000Z
3   2024-12-31T00:00:00.000Z
4   2025-01-03T00:00:00.000Z
..                       ...
75  2025-01-31T00:00:00.000Z
76  2025-01-31T00:00:00.000Z
77  2025-02-01T00:00:00.000Z
78  2025-02-01T00:00:00.000Z
79  2025-02-01T00:00:00.000Z

                                                Title        Category  \
0     Hote booking at Phuket Meet Holiday Hotel-Rawai           Hotel
1                                namaka resort kamala           Hotel
2                                      phi phi hotel            Hotel
3                                        Closing 2024         General
4                                   Rent January 2025            Home
..                                                ...             ...
75  bota kho yao yai loh lak pier to tian sin pier...  Transportation
76                             Taxi to pier to Phuket  Transportation
77                                     Ultimos 2 7/11  Food and Drink
78                                 Taxi a HKT airport            Taxi
79                                    ultimo desayuno  Food and Drink

          Grouping  Amount                Paid By
0   Transportation  152300  3lNLhHQKb1t7WnMKMxiqb
1   Transportation  165200  3lNLhHQKb1t7WnMKMxiqb
2   Transportation  191300  3lNLhHQKb1t7WnMKMxiqb
3    Uncategorized   60000  1NUuvMekM2Wm-mnEmLIld
4             Home  551173  1NUuvMekM2Wm-mnEmLIld
..             ...     ...                    ...
75  Transportation    9600  3lNLhHQKb1t7WnMKMxiqb
76  Transportation    3634  1NUuvMekM2Wm-mnEmLIld
77  Food and Drink    9000  3lNLhHQKb1t7WnMKMxiqb
78  Transportation    6700  3lNLhHQKb1t7WnMKMxiqb
79  Food and Drink    4600  1NUuvMekM2Wm-mnEmLIld

[80 rows x 6 columns]

In [14]:
import json
import pandas as pd

with open('Spliit Export - 2025-02-01.json', 'r') as f:
    data = json.load(f)

expenses_list = []
for expense in data['expenses']:
    expenses_list.append({
        'Paid By': expense['paidById'],
        'Amount': expense['amount']
    })

df = pd.DataFrame(expenses_list)

# Group by 'Paid By' and sum the 'Amount'
total_paid_by_each = df.groupby('Paid By')['Amount'].sum().reset_index()

print(total_paid_by_each)


#If you want to merge it with the participants names:

participants_dict = {p['id']: p['name'] for p in data['participants']}

total_paid_by_each['Payer Name'] = total_paid_by_each['Paid By'].map(participants_dict)

print("\nWith Payer Names:")
print(total_paid_by_each)

                 Paid By   Amount
0  1NUuvMekM2Wm-mnEmLIld   798444
1  3lNLhHQKb1t7WnMKMxiqb  1120500

With Payer Names:
                 Paid By   Amount      Payer Name
0  1NUuvMekM2Wm-mnEmLIld   798444  Prince-Szymsza
1  3lNLhHQKb1t7WnMKMxiqb  1120500         Szymszu

In [15]:
1120500-798444

322056

In [17]:
import json
import pandas as pd

with open('Spliit Export - 2025-02-01.json', 'r') as f:
    data = json.load(f)

expenses_list = []
for expense in data['expenses']:
    for paid_for in expense['paidFor']:
        expenses_list.append({
            'Paid By': expense['paidById'],
            'Paid For': paid_for['participantId'],  # Added Paid For
            'Amount': expense['amount'] * (paid_for['shares'] / 100) if paid_for['shares'] > 0 else 0 # Amount divided by shares, handle 0 shares
        })

df = pd.DataFrame(expenses_list)


total_paid_by_each = df.groupby('Paid By')['Amount'].sum().reset_index()

participants_dict = {p['id']: p['name'] for p in data['participants']}
total_paid_by_each['Payer Name'] = total_paid_by_each['Paid By'].map(participants_dict)


print(total_paid_by_each)

#Total amount spent by each participant (what they paid for):
total_spent_by_each = df.groupby('Paid For')['Amount'].sum().reset_index()
total_spent_by_each['Participant Name'] = total_spent_by_each['Paid For'].map(participants_dict)

print("\nTotal spent by each participant:")
print(total_spent_by_each)

                 Paid By      Amount      Payer Name
0  1NUuvMekM2Wm-mnEmLIld  1331545.04  Prince-Szymsza
1  3lNLhHQKb1t7WnMKMxiqb  2182114.00         Szymszu

Total spent by each participant:
                Paid For      Amount Participant Name
0  1NUuvMekM2Wm-mnEmLIld  1698766.02   Prince-Szymsza
1  3lNLhHQKb1t7WnMKMxiqb  1814893.02          Szymszu

In [22]:
import json
import pandas as pd

with open('Spliit Export - 2025-02-01.json', 'r') as f:
    data = json.load(f)

expenses_list = []
for expense in data['expenses']:
    if expense['title'] == 'ultimo desayuno':  # Filter for the specific expense
        for paid_for in expense['paidFor']:
            expenses_list.append({
                'Paid By': expense['paidById'],
                'Paid For': paid_for['participantId'],
                'Amount': expense['amount']  (paid_for['shares']) ##shares of person / total shares
            })

df = pd.DataFrame(expenses_list)

# Group by 'Paid By' and sum the 'Amount'
total_paid_by_each = df.groupby('Paid By')['Amount'].sum().reset_index()

participants_dict = {p['id']: p['name'] for p in data['participants']}
total_paid_by_each['Payer Name'] = total_paid_by_each['Paid By'].map(participants_dict)

print(total_paid_by_each)

                 Paid By  Amount      Payer Name
0  1NUuvMekM2Wm-mnEmLIld    92.0  Prince-Szymsza